### ISSUE TITLE
3.15 ~ 3.21 TODO List

### ISSUE THREAD

**Issue by youngjun0627** [AlgoSolved/AlgoSolved#56]
## 추가 기능
- 유저에게 푼 지 오래된 코드를 리마인드해주는 기능
- 알림 기능
  - 예를 들어, 레포지토리 연동 작업이 완료됐는지 알려준다.

## study
- infra structure 공부하기 (ec2, load-balancer, ecs) => 지젤
- SonarQube, codecov 등 공부하기

### uchan
- User 스펙 깨지는거 확인
- spring boot batch 스터디하고 백그라운드 작업 돌리는거 테스트

### 지젤
- githubRepository sync 작업을 백그라운드로 돌리기 (spring 에서 비동기 처리)

### 사라
- sourceCode 문자열 길이 제한 테스트보완
- spring boot batch 스터디하고 백그라운드 작업 돌리는거 테스트

**Comment by rha6780** [comment]
시간이 오래 지나 close 하겠습니다.
