### ISSUE TITLE
4.12 ~ 4.18 TODO List

### ISSUE THREAD

**Issue by youngjun0627** [AlgoSolved/AlgoSolved#58]
### uchan
- spring boot batch & async annotation 공부
- infra structure 설계 (코멘트에 설계한 이미지 첨부해서 올리기)
### sara
- spring boot batch & async annotation 공부
- infra structure 설계 (코멘트에 설계한 이미지 첨부해서 올리기)
### giselle
- spring boot batch & async annotation 공부
- infra structure 설계 (코멘트에 설계한 이미지 첨부해서 올리기)

**Comment by mmmtobezip** [comment]
![스크린샷 2024-04-18 오후 6 37 05](https://github.com/AlgoSolved/AlgoSolved/assets/101625865/ed6a5e85-d93e-41bf-90cd-a6a8d68ff4ad)

**Comment by youngjun0627** [comment]
<img width="1026" alt="image" src="https://github.com/AlgoSolved/AlgoSolved/assets/57058726/697c114e-b820-409a-a50e-033438ac1d18">
